### ISSUE TITLE
Test suite started to fail

### ISSUE THREAD

**Issue by eserte** [glauschwuffel/perl5-App-autotest#17]
Looking at http://matrix.cpantesters.org/?dist=App-autotest;reports=1#sl=7,1 the test suite started to fail one-two months ago.

**Comment by glauschwuffel** [comment]
Hm ... interesting. I didn’t change anything. Might the refactoring of Test::More and friends be the reason for this?

**Comment by eserte** [comment]
According to http://analysis.cpantesters.org/solved?distv=App-autotest-0.005 it could be anything... Test::Differences, Test::Harness, Moose...

**Comment by eserte** [comment]
It seems that Test-Differences-0.63 is causing the problem. I generated a pass right now with Test-Differences-0.62 as a prerequisite.

**Comment by glauschwuffel** [comment]
App-autotest-0.005 is a little bit outdated. What option would you choose: Correct the dependency in 0.005 and re-release it or simply delete it from CPAN?

**Comment by eserte** [comment]
As being just a cpantester and not a user of your app, I don't have a real opinion. If you really think the app is a deletion candidate, then you should probably first check http://neilb.org/2013/12/21/deleting-from-cpan.html

**Comment by glauschwuffel** [comment]
Wait ... I don’t want to delete the whole app, just an outdated version. :-)

I think I’ll just correct the dependency. Thanks for the hint!

**Comment by eserte** [comment]
OK :-) Deleting is OK, old versions may be found on backpan anyway.

**Comment by glauschwuffel** [comment]
Fixed with 0969b765a710cf45c462fa5d45e1d9ddff8177dd
Thanks for reporting and sorry it took me so long to fix it!
